---
- name: ansible Play
  hosts: localhost
  become: yes
  tasks:
   - name: install firewalld
     yum: 
      name: firewalld
      state: lastest
     notify: start firewalld  
   - name: install httpd
     yum:
        name: httpd
        state: lastest
     notify: start httpd    
  handlers:
   - name: start firewalld
     service:
      name: firewalld
      state: started 
   - name: start httpd
      service:
       name: httpd
       state: started     