---
- name: ansible Play
  hosts: localhost
  become: yes
  tasks:
   - name: install httpd
     yum:
        name: httpd
        state: lastest
   - name: start httpd
     service :
        name: httpd
        state: started           