---
- name: ansible Play
  hosts: localhost
  become: yes
  tasks:
   - name: install firewalld
     yum: 
      name: firewalld
      state: latest
     notify: start firewalld  
   - name: install httpd
     yum:
      name: httpd
      state: latest
     notify: start httpd
   - name: install mariadb
     yum:
      name: mariadb-server
      state: latest      
  handlers:
   - name: start firewalld
     service:
      name: firewalld
      state: started 
   - name: start httpd
     service:
      name: httpd
      state: started 
   - name: install mariadb
     service:
      name: mariadb
      state: started
      